USE ratings;
INSERT INTO ratings (name, rating, region) VALUES ('John Doe', '5', 'North America');
INSERT INTO ratings (name, rating, region) VALUES ('Jane Smith', '4', 'Europe');
INSERT INTO ratings (name, rating, region) VALUES ('Alice Johnson', '3', 'Asia');
INSERT INTO ratings (name, rating, region) VALUES ('Bob Brown', '4', 'Australia');
INSERT INTO ratings (name, rating, region) VALUES ('Charlie Davis', '5', 'South America');
INSERT INTO ratings (name, rating, region) VALUES ('David Wilson', '2', 'North America');
INSERT INTO ratings (name, rating, region) VALUES ('Eva Martinez', '4', 'Europe');
INSERT INTO ratings (name, rating, region) VALUES ('Frank Moore', '5', 'Asia');
INSERT INTO ratings (name, rating, region) VALUES ('Grace Lee', '3', 'North America');
INSERT INTO ratings (name, rating, region) VALUES ('Henry Taylor', '5', 'Africa');
INSERT INTO ratings (name, rating, region) VALUES ('Ivy Anderson', '2', 'Australia');
INSERT INTO ratings (name, rating, region) VALUES ('Jack Thomas', '4', 'South America');
INSERT INTO ratings (name, rating, region) VALUES ('Katherine Garcia', '3', 'Europe');
INSERT INTO ratings (name, rating, region) VALUES ('Leo Rodriguez', '5', 'North America');
INSERT INTO ratings (name, rating, region) VALUES ('Megan Harris', '2', 'Africa');
INSERT INTO ratings (name, rating, region) VALUES ('Nancy Clark', '4', 'Asia');
INSERT INTO ratings (name, rating, region) VALUES ('Oliver Scott', '3', 'South America');
INSERT INTO ratings (name, rating, region) VALUES ('Paul Young', '5', 'Europe');
INSERT INTO ratings (name, rating, region) VALUES ('Quincy Hall', '2', 'North America');
