name: Data Engineering Practice Pipeline

on:
  push:
    branches: [ main, streamlit_view ]
  pull_request:
    branches: [ main, streamlit_view ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas notebook nbconvert nbval flake8

    - name: Lint Python files
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test Jupyter Notebooks
      run: |
        pytest --nbval --disable-warnings Chapter_1/LoadingDataFromFiles/readFile.ipynb || true
